- name: Deploy Application
  hosts: localhost
  become: yes

  tasks:
    - name: GitLeaks Check
      shell: |
        gitleaks detect --source /var/lib/jenkins/workspace/BoardGame-CI/ --report-path leaks.html 

    - name: Maven Compile
      shell: |
        {{ maven_path }} compile -Dmaven.repo.local=/var/lib/jenkins/.m2/repository
      args:
        chdir: /var/lib/jenkins/workspace/BoardGame-CI/

    - name: Maven Test
      shell: |
        "{{ maven_path }} test"
      args:
        chdir: /var/lib/jenkins/workspace/BoardGame-CI/

    - name: Trivy fs Scan
      shell: |
        trivy fs /var/lib/jenkins/workspace/BoardGame-CI/ --format table -o trivy-fs-scan.html

    - name: SonarQube Scan
      shell: |
        {{ sonar_scanner }}/bin/sonar-scanner \
          -Dsonar.projectKey=Boardgame \
          -Dsonar.sources=. \
          -Dsonar.projectName=Boardgame \

    - name: Maven Build
      shell: |
        "{{ maven_path }} clean package"
      args:
        chdir: /var/lib/jenkins/workspace/BoardGame-CI/

    - name: Docker Build & Tag
      shell: |
        docker build -t yukesh24/boardgame:latest .

    - name: Trivy Image Scan
      shell: |
        trivy image yukesh24/boardgame:latest --format table -o trivy-image-scan.html

    - name: Docker Login to Docker Hub
      community.docker.docker_login:
        username: "{{ DOCKER_HUB_USERNAME }}"
        password: "{{ DOCKER_HUB_PASSWORD }}"

    - name: Docker Push to Docker Hub
      shell: |
        docker push yukesh24/boardgame:latest 

    - name: Docker Logout from Docker Hub
      community.docker.docker_login:
        username: "{{ DOCKER_HUB_USERNAME }}"
        password: "{{ DOCKER_HUB_PASSWORD }}"
        state: absent
